### ISSUE TITLE
[User Interface] Range + Number field

### ISSUE THREAD

**Issue by Zeugh-eth** [blockful-io/shutter-staking-dapp#13]
## These two sibling components have synched data!
This is the nicest challenge of the dApp frontEnd: whenever range filter is updated, the number value in input field is also updated and the same happens in the other way back, whenever input filter is updated: the range filter is also synched!

### **References**

![Image](https://github.com/blockful-io/shutter-staking-dapp/assets/49823133/35d73a2f-edb1-476f-a5b6-a6ceac920000)

https://www.figma.com/design/WeE7ad6ZzrqGw3hiqIfm8s/Shutter-Staker-[V1.1]?node-id=22-761&m=dev

### **For building a good component**

- [ ] Make input number formatting the same as the default number formatting of the application
- [x] Make input number update range filter
- [x] Make input number update range filter
- [x] Make range filter have the minimum of 1
- [x] Make label a custom string

**Comment by edulennert** [comment]
@FrancoAguzzi This PR should be ignored. Use https://github.com/blockful-io/shutter-staking-dapp/pull/29 to test / review instead
