### ISSUE TITLE
[User Interface] Number displaying component

### ISSUE THREAD

**Issue by Zeugh-eth** [blockful-io/shutter-staking-dapp#3]
*Goal:*
Create Ui component for displaying numbers in Shutter Staking dApp. 

*Variations:*
- Big Number
- Small Number
- Primary Number
- Secondary Number

![Image](https://github.com/blockful-io/shutter-staking-dapp/assets/49823133/7a2fb92b-9e7f-4052-8746-d659cebeccbd)

**Comment by FrancoAguzzi** [comment]
`NumberValue` component was created with `label`, `displaySize` and `numberDisplayStyle` props:



https://github.com/blockful-io/shutter-staking-dapp/assets/49823133/52e99e31-3ecb-4146-91ff-300fbe2360e7
