### ISSUE TITLE
[User Interface] Configure standard colors and fonts

### ISSUE THREAD

**Issue by Zeugh-eth** [blockful-io/shutter-staking-dapp#4]
*Goal:*
The goal of this task is towards the maturity of a component library: we want to define standard colors and font families in Shutter Staking dApp in order to reuse these variables across the multiple interface locations that will paint or customize fonts, borders, backgrounds, etc. This should prevent future maintenance headaches and make it possible for the application to be highly customizable with few variable updates. 

*Specs:*

Font-family: [DM Sans](https://fonts.google.com/specimen/DM+Sans)

Colors:
- #FFF
- #D4ED7A
- rgba(212, 237, 122, 1)
- rgba(64, 180, 196, 1)
- #2E383E
- #1E282D
- rgba(212, 237, 122, 0.12)
- rgba(64, 180, 196, 0.12)

**Comment by FrancoAguzzi** [comment]
`tailwind.config.ts` was configured with application default colors + DM Sans font-family import from Google Fonts was added and a `font-dm` exposed to the application for usage of this default font-family.
